### ISSUE TITLE
App Store on some iPads only showing Android builds

### ISSUE THREAD

**Issue by mkm12789** [applivery/roadmap#87] opened 2019-12-20 19:33 UTC
**Describe the bug**
Browsing the App Store on an iPad Air shows Android apps (using Safari). 

**To Reproduce**
I'm using an iPad Pro 12.9-inch (3rd generation). 

User agent details
https://www.whatismybrowser.com/w/WWFFNGD
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Safari/605.1.15

**Expected behavior**
iOS builds will show up

**Comment by CesarTrigo** [comment] 2019-12-20 21:09
@mkm12789 thank you for the report. We will consider this behaviour as a bug.
We will move it under investigation but it pretty much seems to be related with the "unrecognizable" User Agent of the new iPad Pro that looks like an standar Safari Browser.

**Comment by CesarTrigo** [comment] 2020-01-13 17:55
Reproduced and expected to be fixed by the end of Jan 2020.

**Comment by CesarTrigo** [comment] 2020-01-20 07:40
Hi again @mkm12789.
The team has been working on reproducing and solve this issue. In the process we also found some other related issues that should also be fixed.

Since the detection of the iPad Pros is becoming quite difficult, **¿may I ask you to confirm if it has been fixed on your side before closing the issue?**

I look forward to hearing from you.

Thank you,
C.

**Closed** 2020-02-24 13:20 UTC
Labels: bug
