### ISSUE TITLE
Safari Store Site Issues

### ISSUE THREAD

**Issue by mkm12789** [applivery/roadmap#112] opened 2020-02-19 22:00 UTC
**Describe the bug**
When browsing to our Store Site via an iPhone 6 Plus with iOS 11.0.3 using Safari 11, the page does not display correctly. When I do try to login by entering and submitting my credentials, the login page just reloads with empty email/pw fields.
The same behavior happens whether I navigate directly to the URL or use the dashboard (which displays and functions properly) and navigating using the link from there.
 
**To Reproduce**
1. Using and iPhone 6 Plus with iOS 11, browse to an Applivery Store Site

**Expected behavior**
The Store Site to function properly like many other devices

**Screenshots**
![Screen Shot 2020-02-19 at 1 36 42 PM](https://user-images.githubusercontent.com/1542685/74880343-dd4b1b80-531f-11ea-99c3-9498a676849a.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 6 Plu
 - OS: iOS 11.0.3
 - Browser: Safari
 - Version: 11

**Additional Notes**
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_0_3 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A432 Safari/604.1

**Comment by mkm12789** [comment] 2020-02-20 19:11
Initially this was reported to me with just the iPhone 6 but now many people are complaining the same thing is happening on several iOS devices when using Safari. I was even able to reproduce the issue on my iMac with Safari

**Comment by CesarTrigo** [comment] 2020-02-24 21:09
@mkm12789 after some research the issue is related with a Safari issue with SSL & TLS protocol that is fixed in the newest versions of the browser. We have implemented a fix and it has been released a few minutes ago.

**Closed by CesarTrigo** 2020-02-24 21:09 UTC
Labels: App Store

**Comment by mkm12789** [comment] 2020-02-24 23:29
Thank you very much @CesarTrigo!!
