### ISSUE TITLE
iPadOS 13 Cannot Install Apps from Distribution Sites

### ISSUE THREAD

**Issue by mkm12789** [applivery/roadmap#77] opened 2019-10-01 22:27 UTC
**Describe the bug**
iOS 13 changed the way Safari displays Distribution Sites. It gets the view as if the site is being viewed on the desktop and the "Install" button is greyed out. 

**To Reproduce**
1. Using an iPad (my team says it happens on all iPads) with the latest iOS13, browse to a Distribution site with an iOS build

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Safari
 - Version iOS13

**Comment by CesarTrigo** [comment] 2019-10-02 06:29
Hi @mkm12789, thank you for the report.
Unfortunately, the new **iPadOS 13** modifies the behaviour of the Safari nativaton User Agent to always request by default the Desktop version of any webpage, including ours. That makes us think you are navigating with a MacBook instead of an iPad since the User Agent is exactly the same and there's no way to differentiate one from the other...

We are working on a permanent fix by detecting the touch screen and/or touch events and an updated view for iPads.

In the meantime you have 2 options:
* You can continue using Applvery with Safari  by enabling the **Request Desktop Website** at `Settings -> Safari -> Request Desktop Website`. However it will affect all the webpages (as it was in the previous iPad OS version).
* You can install **Google Chrome** and use it as usual.

**Comment by mkm12789** [comment] 2020-01-24 19:02
For future reference, solution 1, safari in desktop mode, did not work for our iPad Air 3rd gen using 13.1.2. 
Solution 2, using chrome, works just fine

**Comment by mkm12789** [comment] 2020-02-18 21:19
Just to add to the notes, an iPad 10.2" 7th Gen (Wi-Fi Only) also had this problem on iOS 13.2

**Comment by CesarTrigo** [comment] 2020-02-18 21:28
Hi @mkm12789 we closed this issue a few weeks ago after some changes that should have fixed the error. Does that means that you are still facing the issue in iPad Pros or just in Air and 10.2? Can you please share an screenshot of both just before clicking the "Install" button?
- iPad Air
- iPad 10.2

Thank you,

**Comment by mkm12789** [comment] 2020-02-18 21:50
This is the first I've heard this issue coming up from our company in some time but I'm not sure if that's just because everyone switched to Chrome (which is what I'm continuing to tell people to do). 
The recent issue was on Safari with the 7th Gen iPad.
To reproduce:
1. Navigate to Distribution Site
2. Click "INSTALL"
3. Overlay appears with "The app is being installed in your Homescreen!"
4. iOS dialog box appears with the text 'Do you want to download "[ipa name]"?'
5. Clicking the Download option just downloads the .ipa as a file in Safari. If you open the .ipa after it's downloaded, you're just shown information about the file but it is not installed.

I've attached the screenshot of the dialog box.
![Screen Shot 2020-02-18 at 1 40 08 PM](https://user-images.githubusercontent.com/1542685/74780657-e8854500-5254-11ea-947d-65a82ee98d38.png)

Also here's the User Agent if that helps:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15

**Comment by CesarTrigo** [comment] 2020-02-19 06:30
Thank you @mkm12789,
We managed to reproduce the issue. It is being fixed and will be deployed in the next release (most probably by today or tomorrow) along with some other minor fixes.
Regards,
C.

**Comment by CesarTrigo** [comment] 2020-02-24 13:20
Hi @mkm12789 this issue should be fixed. Can you please try again and confirm? I'll tentatively close the issue but feel free to reopen it if something goes wrong.
Thank you.
C.

**Closed by CesarTrigo** 2020-02-24 13:20 UTC
Labels: bug, enhancement
